#ifndef WEBPAGE_H_
#define WEBPAGE_H_
typedef struct
{
const char *filename;//Dateiname der Seite
PGM_P page_pointer;//Zeiger auf Speicherinhalt
}
PGM_WebItem;
const PROGMEM char index_html[] = {
"<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"rocrail.net\">\n"
"<html>\n"
"    <head>\n"
"        <meta http-equiv=\"content-type\" content=\"text/html; charset=ISO-8859-1\">\n"
"         <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"> \n"
"            <title>Ethernet Decoder: Home</title>\n"
"		\n"
"		<link rel=\"stylesheet\" type=\"text/css\"  href=\"styles.css\">\n"
"		\n"
"		<style type=\"text/css\"> \n"
"	\n"
"	* {\n"
"	  -webkit-touch-callout: none; /* prevent callout to copy image, etc when tap to hold */\n"
"	  -webkit-text-size-adjust: none; /* prevent webkit from resizing text to fit */\n"
"	/* make transparent link selection, adjust last value opacity 0 to 1.0 */\n"
"	  -webkit-tap-highlight-color: rgba(0,0,0,0); \n"
"	  -webkit-user-select: none; /* prevent copy paste, to allow, change \'none\' to \'text\' */\n"
"	  -webkit-tap-highlight-color: rgba(0,0,0,0); \n"
"	}\n"
"	\n"
"	</style>\n"
"		\n"
"		<script>\n"
"		function openNav() {\n"
"            document.getElementById(\"mySidenav\").style.width = \"250px\";\n"
"            document.getElementById(\"main\").style.marginLeft = \"250px\";\n"
"        }\n"
"        function closeNav() {\n"
"            document.getElementById(\"mySidenav\").style.width = \"0\";\n"
"            document.getElementById(\"main\").style.marginLeft= \"0\";\n"
"        }\n"
"		\n"
"		function vollbild() {\n"
"			var element = document.getElementById(\"inhalt\");\n"
"			if (element.requestFullScreen) {\n"
"				if (!document.fullScreen) {\n"
"					element.requestFullscreen();\n"
"				} else {\n"
"				document.exitFullScreen();\n"
"				}\n"
"			} else if (element.mozRequestFullScreen) {\n"
"				if (!document.mozFullScreen) {\n"
"					element.mozRequestFullScreen();\n"
"				} else {\n"
"					document.mozCancelFullScreen();\n"
"				}\n"
"			} else if (element.webkitRequestFullScreen) {\n"
"				if (!document.webkitIsFullScreen) {\n"
"					element.webkitRequestFullScreen();\n"
"				} else {\n"
"					document.webkitCancelFullScreen();\n"
"				}\n"
"			}		\n"
"		}\n"
"		//document.getElementById(\"vollbild_link\").addEventListener(\"click\", vollbild, false);\n"
"		\n"
"		\n"
"		var Direction=0;\n"
"		var Speed=0;\n"
"		var LightMode=0;\n"
"		var LightFront=0;\n"
"		var LightBack=0;\n"
"		\n"
"		function OnloadFunction(){\n"
"			//vollbild();\n"
"			document.getElementById(\"LightModeValue\").innerHTML = LightMode;\n"
"			document.getElementById(\"LightFrontValue\").innerHTML = LightFront;\n"
"			document.getElementById(\"LightBackValue\").innerHTML = LightBack;\n"
"			nocache = \"nocache=\" + Math.random()*1000000;\n"
"			var request = new XMLHttpRequest();\n"
"				request.onreadystatechange=function()\n"
"				{					\n"
"					if(this.readyState==4 && this.status==200)\n"
"					{\n"
"						if(this.responseXML != null)\n"
"						{\n"
"							//extract XML data from XML file\n"
"							//document.getElementById(\"IPAdr\").value =\n"
"								//this.responseXML.getElementsByTagName(\'IPAdr\')[0].childNodes[0].nodeValue;\n"
"							Direction=this.responseXML.getElementsByTagName(\'DIRECTION\')[0].childNodes[0].nodeValue;\n"
"							Speed=this.responseXML.getElementsByTagName(\'SPEED\')[0].childNodes[0].nodeValue;\n"
"							document.getElementById(\"DirectionValue\").innerHTML = Direction;\n"
"							document.getElementById(\"SpeedValue\").innerHTML = Speed;\n"
"							document.getElementById(\"SpeedSlider\").value=Speed*Direction;\n"
"						}\n"
"					}\n"
"				}\n"
"				\n"
"				request.open(\"GET\",\"AjaxControlDataExchange?\"+nocache,true);\n"
"				request.send(null);\n"
"				//setTimeout(\'GetWebserverData()\',200);\n"
"			\n"
"		}\n"
"		\n"
"		function SetDirection(){\n"
"			\n"
"			if(Direction==-1)\n"
"			{\n"
"				Direction=1;\n"
"			}\n"
"			else\n"
"			{\n"
"				Direction=-1;\n"
"			}\n"
"			document.getElementById(\"DirectionValue\").innerHTML = Direction;\n"
"			SendValueFunction();\n"
"		}\n"
"		\n"
"		function SetSpeed(){\n"
"			Speed=document.getElementById(\"SpeedSlider\").value;\n"
"			document.getElementById(\"SpeedValue\").innerHTML = Speed;	\n"
"			SendValueFunction();		\n"
"		}\n"
"		\n"
"		function StopSpeed(){\n"
"			Speed=0;\n"
"			document.getElementById(\"SpeedSlider\").value=Speed;\n"
"			document.getElementById(\"SpeedValue\").innerHTML = Speed;	\n"
"			SendValueFunction();		\n"
"		}\n"
"		\n"
"		function SetLightMode(){\n"
"			if(LightMode==0)\n"
"			{\n"
"				LightMode=1;\n"
"			}\n"
"			else\n"
"			{\n"
"				LightMode=0;\n"
"			}\n"
"			document.getElementById(\"LightModeValue\").innerHTML = LightMode;	\n"
"			SendValueFunction();		\n"
"		}\n"
"		\n"
"		function SetLightFront(){\n"
"			if(LightFront==0)\n"
"			{\n"
"				LightFront=1;\n"
"			}\n"
"			else\n"
"			{\n"
"				LightFront=0;\n"
"			}\n"
"			document.getElementById(\"LightFrontValue\").innerHTML = LightFront;	\n"
"			SendValueFunction();		\n"
"		}\n"
"		\n"
"		function SetLightBack(){\n"
"			if(LightBack==0)\n"
"			{\n"
"				LightBack=1;\n"
"			}\n"
"			else\n"
"			{\n"
"				LightBack=0;\n"
"			}\n"
"			document.getElementById(\"LightBackValue\").innerHTML = LightBack;	\n"
"			SendValueFunction();		\n"
"		}\n"
"		\n"
"		function SendValueFunction() {\n"
"				nocache = \"&nocache=\" + Math.random()*1000000;\n"
"				var request = new XMLHttpRequest();\n"
"				request.onreadystatechange=function()\n"
"				{					\n"
"					if(this.readyState==4 && this.status==200)\n"
"					{\n"
"						if(this.responseXML != null)\n"
"						{\n"
"							//extract XML data from XML file\n"
"							//document.getElementById(\"IPAdr\").value =\n"
"								//this.responseXML.getElementsByTagName(\'IPAdr\')[0].childNodes[0].nodeValue;\n"
"						}\n"
"					}\n"
"				}\n"
"				\n"
"				request.open(\"GET\",\"AjaxControlDataExchange?SpeedValue=\"+Speed+\"&DirectionValue=\"+Direction+\"&LightMode=\"+LightMode+\"&LightFront=\"+LightFront+\"&LightBack=\"+LightBack+nocache,true);\n"
"				request.send(null);\n"
"				//setTimeout(\'GetWebserverData()\',200);\n"
"			}	\n"
"			\n"
"		</script>\n"
"		\n"
"		\n"
"	</head>\n"
"	<body id=\"inhalt\" onload=\"OnloadFunction()\" >\n"
"        <header>\n"
"		<span style=\"float: left; cursor:pointer\" onclick=\"openNav()\">&#9776; Men&#252;</span>\n"
"		<h1 style=\"float: center;\" >Home</h1>\n"
"        </header>\n"
"<div id=\"mySidenav\" class=\"sidenav\">\n"
"  <a href=\"javascript:void(0)\" class=\"closebtn\" onclick=\"closeNav()\">&times;</a>\n"
"  <a href=\"index.html\">Home</a>\n"
"  <a href=\"config.html\">Config</a>\n"
"  <a href=\"status.html\">Status</a>\n"
"</div>\n"
"        <hr>\n"
"		<p>\n"
"		<button id=\"FrontButton\" onclick=\"SetLightFront()\" style=\"margin: 40px;\">Front</button>\n"
"		<button id=\"BackButton\" onclick=\"SetLightBack()\" style=\"margin: 40px;\">Back</button>\n"
"        <button id=\"ModeButton\" onclick=\"SetLightMode()\" style=\"margin: 40px;\">Mode</button>\n"
"		<br/>        \n"
"		<button id=\"DirectionButton\" onclick=\"SetDirection()\" style=\"margin: 40px;\">Direction</button>\n"
"        <button id=\"StopButton\" onclick=\"StopSpeed()\" style=\"margin: 40px;\">STOP</button>\n"
"		</p>\n"
"<div class=\"slidecontainer\" style=\"margin: 40px;\">\n"
"  <input type=\"range\" min=\"0\" max=\"100\" value=\"0\" class=\"slider\" id=\"SpeedSlider\" oninput=\"SetSpeed()\">\n"
"</div>\n"
"	<br>\n"
"		<p>\n"
"		<span id=\"LightFrontValue\" style=\"margin: 40px;\">...</span>\n"
"		<span id=\"LightModeValue\" style=\"margin: 40px;\">...</span>\n"
"		<span id=\"LightBackValue\" style=\"margin: 40px;\">...</span>\n"
"		</p>\n"
"        <p><span id=\"SpeedValue\" style=\"margin: 40px;\">...</span> <span id=\"DirectionValue\" style=\"margin: 40px;\">...</span></p>\n"
"        <br/>\n"
"	<p><button id=\"ScreenButton\" onclick=\"vollbild()\" style=\"margin: 40px;\">Fullscreen</button></p>\n"
"		\n"
"	<br>	\n"
"	<tail><a href=\"http://www.rocrail.net\">www.rocrail.net</a> Marcel Maage 2018</tail>\n"
"	</body>\n"
"</html>\n"
""};
const PROGMEM char config_html[] = {
"<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"rocrail.net\">\n"
"<html>\n"
"    <head>\n"
"        <meta http-equiv=\"content-type\" content=\"text/html; charset=ISO-8859-1\">\n"
"        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"> \n"
"            <title>Ethernet Decoder : Config</title>\n"
"		<link rel=\"stylesheet\" type=\"text/css\"  href=\"styles.css\">\n"
"		\n"
"	</head>\n"
"	<body onload=\"GetWebserverData()\" id=\"inhalt\">\n"
"	<header>\n"
"		<span style=\"float: left; cursor:pointer\" onclick=\"openNav()\">&#9776; Men&#252;</span>\n"
"		<h1 style=\"float: center;\" >Config</h1>\n"
"    </header>\n"
"    \n"
"    <div id=\"mySidenav\" class=\"sidenav\">\n"
"        <a href=\"javascript:void(0)\" class=\"closebtn\" onclick=\"closeNav()\">&times;</a>\n"
"        <a href=\"index.html\">Home</a>\n"
"        <a href=\"config.html\">Config</a>\n"
"        <a href=\"status.html\">Status</a>\n"
"    </div>\n"
"    \n"
"	<br>\n"
"	<h2>mDNS</h2>\n"
"	<input type=\"text\" name=\"MDNSNAME\" id=\"mDNSName\" value=\"LokControlDefault\"/>\n"
"	<br>\n"
"	<hr>\n"
"	<h2>WLAN Station</h2>\n"
"	<p>Name:<p/>\n"
"    <br/>\n"
"	<input type=\"text\" name=\"STNAME\" id=\"STName\" value=\"\"/>\n"
"	<br/>\n"
"	<p>Passwort:<p/>\n"
"    <br/>\n"
"	<input type=\"text\" name=\"STPWD\" id=\"STPwd\" value=\"\"/>\n"
"	<br>\n"
"	<br>\n"
"        <hr>\n"
"        \n"
"        <h2>AP</h2>\n"
"        <p>Name:<p/>\n"
"        <input type=\"text\" name=\"APNAME\" id=\"APName\" value=\"APName\"/>\n"
"        <br>\n"
"        <p>Passwort:<p/>\n"
"        <input type=\"text\" name=\"APPWD\" id=\"APPwd\" value=\"APPasswort\"/>\n"
"        <br>\n"
"        <hr>\n"
"        <h2>Netzwerkkonfiguration</h2>\n"
"        <p>IP-Adresse:<p/>\n"
"                <br/>\n"
"        <input type=\"text\" name=\"IP\" required pattern=\"^([0-9]{1,3}\\.){3}[0-9]{1,3}$\" id=\"IPAdr\" value=\"192.168.2.95\"/>\n"
"	<br/>\n"
"        <p>Netzmaske:<p/>\n"
"        <input type=\"text\" name=\"NM\" required pattern=\"^([0-9]{1,3}\\.){3}[0-9]{1,3}$\" id=\"NETMSK\" value=\"255.255.255.0\"/>\n"
"	<br/>\n"
"        <p>Router-IP:<p/>\n"
"        <input type=\"text\" name=\"Rtr\" required pattern=\"^([0-9]{1,3}\\.){3}[0-9]{1,3}$\" id=\"IPRtr\" value=\"192.168.2.1\"/>\n"
"	<br/>\n"
"        <p>Rocrailport:<p/>\n"
"        <input type=\"number\" name=\"Prt\" id=\"ROCPort\" value=\"4444\"/>\n"
"	<br/>\n"
"	<p><button id=\"ButtonSpeichern\" onclick=\"AjaxConfigDataExchange()\">Speichern</button></p>\n"
"	\n"
"	\n"
"	<tail><a href=\"http://www.rocrail.net\">www.rocrail.net</a> Marcel Maage 2018</tail>\n"
"	\n"
"	<script>\n"
"        function openNav() {\n"
"            document.getElementById(\"mySidenav\").style.width = \"250px\";\n"
"            document.getElementById(\"main\").style.marginLeft = \"250px\";\n"
"        }\n"
"        function closeNav() {\n"
"            document.getElementById(\"mySidenav\").style.width = \"0\";\n"
"            document.getElementById(\"main\").style.marginLeft= \"0\";\n"
"        }\n"
"	\n"
"			function GetWebserverData()\n"
"			{\n"
"				vollbild();\n"
"				var request = new XMLHttpRequest();\n"
"				request.onreadystatechange=function()\n"
"				{\n"
"					if(this.readyState==4 && this.status==200)\n"
"					{\n"
"						if(this.responseXML != null)\n"
"						{\n"
"							//extract XML data from XML file\n"
"							document.getElementById(\"mDNSName\").value =\n"
"								this.responseXML.getElementsByTagName(\'mDNSName\')[0].childNodes[0].nodeValue;\n"
"							document.getElementById(\"STName\").value =\n"
"								this.responseXML.getElementsByTagName(\'STName\')[0].childNodes[0].nodeValue;\n"
"                            document.getElementById(\"STPwd\").value =\n"
"								this.responseXML.getElementsByTagName(\'STPwd\')[0].childNodes[0].nodeValue;\n"
"							document.getElementById(\"APName\").value =\n"
"								this.responseXML.getElementsByTagName(\'APName\')[0].childNodes[0].nodeValue;\n"
"                            document.getElementById(\"APPwd\").value =\n"
"								this.responseXML.getElementsByTagName(\'APPwd\')[0].childNodes[0].nodeValue;\n"
"							document.getElementById(\"IPAdr\").value =\n"
"								this.responseXML.getElementsByTagName(\'IPAdr\')[0].childNodes[0].nodeValue;\n"
"							document.getElementById(\"NETMSK\").value =\n"
"								this.responseXML.getElementsByTagName(\'NETMSK\')[0].childNodes[0].nodeValue;\n"
"							document.getElementById(\"IPRtr\").value =\n"
"								this.responseXML.getElementsByTagName(\'IPRtr\')[0].childNodes[0].nodeValue;\n"
"							document.getElementById(\"ROCPort\").value =\n"
"								this.responseXML.getElementsByTagName(\'ROCPort\')[0].childNodes[0].nodeValue;\n"
"						}\n"
"					}\n"
"				}\n"
"				request.open(\"GET\",\"AjaxConfigDataExchange\",true);\n"
"				request.send(null);	\n"
"				\n"
"			}\n"
"			\n"
"			function vollbild() {\n"
"			var element = document.getElementById(\"inhalt\");\n"
"			if (element.requestFullScreen) {\n"
"				if (!document.fullScreen) {\n"
"					element.requestFullscreen();\n"
"				} else {\n"
"				document.exitFullScreen();\n"
"				}\n"
"			} else if (element.mozRequestFullScreen) {\n"
"				if (!document.mozFullScreen) {\n"
"					element.mozRequestFullScreen();\n"
"				} else {\n"
"					document.mozCancelFullScreen();\n"
"				}\n"
"			} else if (element.webkitRequestFullScreen) {\n"
"				if (!document.webkitIsFullScreen) {\n"
"					element.webkitRequestFullScreen();\n"
"				} else {\n"
"					document.webkitCancelFullScreen();\n"
"				}\n"
"			}		\n"
"			}\n"
"			\n"
"			function AjaxConfigDataExchange()\n"
"			{\n"
"				var request = new XMLHttpRequest();\n"
"				request.onreadystatechange=function()\n"
"				{\n"
"					if(this.readyState==4 && this.status==200)\n"
"					{\n"
"						if(this.responseXML != null)\n"
"						{\n"
"							//extract XML data from XML file\n"
"							document.getElementById(\"mDNSName\").value =\n"
"								this.responseXML.getElementsByTagName(\'mDNSName\')[0].childNodes[0].nodeValue;\n"
"							document.getElementById(\"STName\").value =\n"
"								this.responseXML.getElementsByTagName(\'STName\')[0].childNodes[0].nodeValue;\n"
"                            document.getElementById(\"STPwd\").value =\n"
"								this.responseXML.getElementsByTagName(\'STPwd\')[0].childNodes[0].nodeValue;\n"
"                            document.getElementById(\"APName\").value =\n"
"								this.responseXML.getElementsByTagName(\'APName\')[0].childNodes[0].nodeValue;\n"
"                            document.getElementById(\"APPwd\").value =\n"
"								this.responseXML.getElementsByTagName(\'APPwd\')[0].childNodes[0].nodeValue;\n"
"							document.getElementById(\"IPAdr\").value =\n"
"								this.responseXML.getElementsByTagName(\'IPAdr\')[0].childNodes[0].nodeValue;\n"
"							document.getElementById(\"NETMSK\").value =\n"
"								this.responseXML.getElementsByTagName(\'NETMSK\')[0].childNodes[0].nodeValue;\n"
"							document.getElementById(\"IPRtr\").value =\n"
"								this.responseXML.getElementsByTagName(\'IPRtr\')[0].childNodes[0].nodeValue;\n"
"							document.getElementById(\"ROCPort\").value =\n"
"								this.responseXML.getElementsByTagName(\'ROCPort\')[0].childNodes[0].nodeValue;\n"
"						}\n"
"					}\n"
"				}\n"
"				request.open(\"GET\",\"AjaxConfigDataExchange?mDNSName=\"+document.getElementById(\"mDNSName\").value+\"&STName=\"+document.getElementById(\"STName\").value+\"&STPwd=\"+document.getElementById(\"STPwd\").value+\"&APName=\"+document.getElementById(\"APName\").value+\"&APPwd=\"+document.getElementById(\"APPwd\").value+\"&IPAdr=\"+document.getElementById(\"IPAdr\").value+\"&NETMSK=\"+document.getElementById(\"NETMSK\").value+\"&IPRtr=\"+document.getElementById(\"IPRtr\").value+\"&ROCPort=\"+document.getElementById(\"ROCPort\").value,true);\n"
"				request.send(null);				\n"
"			}\n"
"		</script>\n"
"	\n"
"	\n"
"	\n"
"	</body>\n"
"</html>\n"
""};
const PROGMEM char status_html[] = {
"<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://rocrail.net\\\">\n"
"	<html>\n"
"		<head>\n"
"			<meta http-equiv=\"content-type\" content=\"text/html; charset=ISO-8859-1\">\n"
"	        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"> \n"
"	<title>Ethernet Decoder : Status</title>\n"
"	\n"
"	<link rel=\"stylesheet\" type=\"text/css\"  href=\"styles.css\">\n"
"	\n"
"		<script>\n"
"        function openNav() {\n"
"            document.getElementById(\"mySidenav\").style.width = \"250px\";\n"
"            document.getElementById(\"main\").style.marginLeft = \"250px\";\n"
"        }\n"
"        function closeNav() {\n"
"            document.getElementById(\"mySidenav\").style.width = \"0\";\n"
"            document.getElementById(\"main\").style.marginLeft= \"0\";\n"
"        }\n"
"		\n"
"			function GetWebserverData()\n"
"			{\n"
"				nocache = \"?nocache=\" + Math.random()*1000000;\n"
"				var request = new XMLHttpRequest();\n"
"				request.onreadystatechange=function()\n"
"				{\n"
"					if(this.readyState==4 && this.status==200)\n"
"					{\n"
"						if(this.responseXML != null)\n"
"						{\n"
"							//extract XML data from XML file\n"
"							document.getElementById(\"DATE\").innerHTML =\n"
"								this.responseXML.getElementsByTagName(\'DATE\')[0].childNodes[0].nodeValue;\n"
"							document.getElementById(\"TIME\").innerHTML =\n"
"								this.responseXML.getElementsByTagName(\'TIME\')[0].childNodes[0].nodeValue;\n"
"							document.getElementById(\"VERSION\").innerHTML =\n"
"								this.responseXML.getElementsByTagName(\'VERSION\')[0].childNodes[0].nodeValue;\n"
"						}\n"
"					}\n"
"				}\n"
"				request.open(\"GET\",\"AjaxConfigDataExchange\"+nocache,true);\n"
"				request.send(null);\n"
"				//setTimeout(\'GetWebserverData()\',1000);				\n"
"				\n"
"			}\n"
"		</script>\n"
"	\n"
"	\n"
"	</head>\n"
"	<body onload=\"GetWebserverData()\">\n"
"    <header>\n"
"		<span style=\"float: left; cursor:pointer\" onclick=\"openNav()\">&#9776; Men&#252;</span>\n"
"		<h1 style=\"float: center;\" >Status</h1>\n"
"    </header>\n"
"    <div id=\"mySidenav\" class=\"sidenav\">\n"
"        <a href=\"javascript:void(0)\" class=\"closebtn\" onclick=\"closeNav()\">&times;</a>\n"
"        <a href=\"index.html\">Home</a>\n"
"        <a href=\"config.html\">Config</a>\n"
"        <a href=\"status.html\">Status</a>\n"
"    </div>\n"
"    \n"
"	<div id=\"main\">\n"
"	\n"
"	Compiliert am \"<span id=\"DATE\">...</span>\" um \" <span id=\"TIME\">...</span>\"<br><br>\n"
"	Version \"<span id=\"VERSION\">...</span>\"\n"
"	<br/>\n"
"	</div>\n"
"	<h2>Update</h2>\n"
"	<br/>\n"
"	<form method=\'POST\' action=\'/update\' enctype=\'multipart/form-data\'>\n"
"		<input type=\'file\' name=\'update\'><input type=\'submit\' value=\'Update\'>\n"
"	</form>\n"
"	<br/>\n"
"	<br/>\n"
"	\n"
"	<tail><a href=\"http://www.rocrail.net\">www.rocrail.net</a> Marcel Maage 2018</tail>	\n"
"	\n"
"	</body>\n"
"	</html> \n"
""};
const PROGMEM char styles_css[] = {
"	body{margin: 0px;} \n"
"	body,p,div,h1,h2,td,th{font-family:sans-serif;font-size:11px}\n"
"	header{font-size:20px;color:white; background-color:#96B11C;margin:1px;padding:5px;text-align:center;}\n"
"	h1{font-size:20px;color:white; background-color:#96B11C;margin:1px;padding:5px;text-align:center;}\n"
"	h2{font-size:18px;color:#96B11C}\n"
"	p,h2{margin:0px0px5px0px}\n"
"	img{border:0}\n"
"	hr{color:silver; background-color:silver;border:0;height:1px}\n"
"	nav{font-size: 16px; background-color:silver;margin:1px;padding:5px;font-weight:bold}\n"
"	nav a, tail a{color:white; padding:10px;text-decoration:none}\n"
"	nav a:hover,tail a:hover{text-decoration:underline}\n"
"	tail{ color:white; background-color:silver;text-align:center;padding:5px}\n"
"	#main{text-align:center;margin:20px}\n"
"	.clear{clear:left}\n"
"	.tempTbl {table-layout:auto;border-spacing:0}\n"
"	.tempTbl td{text-align:center;padding:7px}\n"
"	.tempTbl th{background-color:silver} \n"
"	.slidecontainer {width: 90%;}\n"
"    .slider {\n"
"    -webkit-appearance: none;\n"
"    appearance: none;\n"
"    width: 100%;\n"
"    height: 25px;\n"
"    background: #d3d3d3;\n"
"    outline: none;\n"
"    opacity: 0.7;\n"
"    -webkit-transition: .2s;\n"
"    transition: opacity .2s;\n"
"    }\n"
"    body {\n"
"    font-family: \"Lato\", sans-serif;\n"
"    transition: background-color .5s;\n"
"}\n"
".sidenav {\n"
"    height: 100%;\n"
"    width: 0;\n"
"    position: fixed;\n"
"    z-index: 1;\n"
"    top: 0;\n"
"    left: 0;\n"
"    background-color: #111;\n"
"    overflow-x: hidden;\n"
"    transition: 0.5s;\n"
"    padding-top: 60px;\n"
"}\n"
".sidenav a {\n"
"    padding: 8px 8px 8px 32px;\n"
"    text-decoration: none;\n"
"    font-size: 25px;\n"
"    color: #818181;\n"
"    display: block;\n"
"    transition: 0.3s;\n"
"}\n"
".sidenav a:hover {\n"
"    color: #f1f1f1;\n"
"}\n"
".sidenav .closebtn {\n"
"    position: absolute;\n"
"    top: 0;\n"
"    right: 25px;\n"
"    font-size: 36px;\n"
"    margin-left: 50px;\n"
"}\n"
"@media screen and (max-height: 450px) {\n"
"  .sidenav {padding-top: 15px;}\n"
"  .sidenav a {font-size: 18px;}\n"
"}\n"
""};
PGM_WebItem WEBPAGE_TABLE[] = // Befehls-Tabelle
{
	{"index.html",index_html},
	{"config.html",config_html},
	{"status.html",status_html},
	{"styles.css",styles_css},
	{NULL,NULL}
};
#endif